version: "3.9"

services:
  auth-service:
    platform: linux/amd64
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      DB_CONNECTION: "postgresql://postgres:postgres@auth-db:5432/auth"
    ports:
      - "8081:8081"
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  recipe-service:
    platform: linux/amd64
    build:
      context: ./recipe-service
      dockerfile: Dockerfile
    container_name: recipe-service
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8081"
      DB_CONNECTION: "postgresql://postgres:postgres@recipe-db:5432/recipe"
      MONGO_DB_CONNECTION: "mongodb://admin:password@recipe-mongo:27017/recipe-db?authSource=admin"
      MONGO_WRITE_DB_CONNECTION: "mongodb://recipe-write-mongo:27017/recipe-db"
    depends_on:
      - auth-service
      - recipe-db
      - recipe-mongo
      - recipe-write-mongo
      - rabbit1
      - rabbit2

    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - recipe-network
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  recipe-db:
    image: postgres:16
    container_name: recipe-db
    restart: always
    environment:
      POSTGRES_DB: recipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - recipe-network
    ports:
      - "5432:5432"
    volumes:
      - recipe_db_data:/var/lib/postgresql/data

  recipe-mongo:
    image: mongo:8.0.20
    container_name: recipe-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recipe_db
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - recipe-network

  recipe-write-mongo:
    image: mongo:8.0.20
    container_name: recipe-write-mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - write_mongo_data:/data/db
      - write_mongo_config:/data/configdb
    networks:
      - recipe-network

  auth-mongo:
    image: mongo:8.0.20
    container_name: auth-mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - auth_mongo_data:/data/db
      - auth_mongo_config:/data/configdb
    networks:
      - recipe-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    depends_on:
      - recipe-service
    networks:
      - recipe-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - recipe-network
  
  redis-ingredient:
    image: redis:7.2-alpine
    container_name: redis-ingredient
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy allkeys-lfu 
      --port 6379
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - recipe-network
  
  redis-recipe:
    image: redis:7.2-alpine
    container_name: redis-recipe
    command: >
      redis-server 
      --maxmemory 200mb 
      --maxmemory-policy allkeys-lfu 
      --port 6380
    ports:
      - "6380:6380"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - recipe-network

  redis-rate-limit:
    image: redis:7.2-alpine
    container_name: redis-rate-limit
    command: >
      redis-server 
      --maxmemory 50mb 
      --maxmemory-policy allkeys-lfu 
      --port 6381
    ports:
      - "6381:6381"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - recipe-network

  rabbit1:
    image: rabbitmq:3.13-management
    container_name: rabbit1
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "SUPER_SECRET_COOKIE"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - recipe-network
    volumes:
      - rabbit1_data:/var/lib/rabbitmq

  rabbit2:
    image: rabbitmq:3.13-management
    container_name: rabbit2
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "SUPER_SECRET_COOKIE"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit2_data:/var/lib/rabbitmq
    networks:
      - recipe-network
    command: >
      bash -c "
        rabbitmq-server &
        sleep 10 &&
        rabbitmqctl stop_app &&
        rabbitmqctl join_cluster rabbit@rabbit1 &&
        rabbitmqctl start_app &&
        tail -f /dev/null
      "

volumes:
  grafana_data:
  auth_db_data:
  recipe_db_data:
  mongo_data:
  mongo_config:
  auth_mongo_data:
  auth_mongo_config:
  write_mongo_data:
  write_mongo_config:
  rabbit1_data:
  rabbit2_data:

networks:
  recipe-network:
    driver: bridge