version: "3.9"

services:
  auth-service:
    platform: linux/amd64
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      DB_CONNECTION: "postgresql://postgres:postgres@auth-db:5432/auth"
    ports:
      - "8081:8081"
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  recipe-service:
    platform: linux/amd64
    build:
      context: ./recipe-service
      dockerfile: Dockerfile
    container_name: recipe-service
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8081"
      DB_CONNECTION: "postgresql://postgres:postgres@recipe-db:5432/recipe"
      MONGO_DB_CONNECTION: "mongodb://admin:password@recipe-mongo:27017/recipe-db?authSource=admin"
    depends_on:
      - auth-service
      - recipe-db
      - recipe-mongo
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3


  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - recipe-network
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  recipe-db:
    image: postgres:16
    container_name: recipe-db
    restart: always
    environment:
      POSTGRES_DB: recipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - recipe-network
    ports:
      - "5432:5432"
    volumes:
      - recipe_db_data:/var/lib/postgresql/data

  recipe-mongo:
    image: mongo:8.0.20
    container_name: recipe-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recipe_db
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - recipe-network
  
  auth-mongo:
    image: mongo:8.0.20
    container_name: auth-mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - auth_mongo_data:/data/db
      - auth_mongo_config:/data/configdb
    networks:
      - recipe-network

volumes:
  auth_db_data:
  recipe_db_data:
  mongo_data:
  mongo_config:
  auth_mongo_data:
  auth_mongo_config:

networks:
  recipe-network:
    driver: bridge