worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: ture
enable_postgres: true

server-port: 8081

public-key-path: ../app/keys/public.pem
private-key-path: ../app/keys/private.pem

# change to URI of your postgres database
